### ISSUE TITLE
File open error when 'make test' runs

### ISSUE THREAD

**Issue by shotarok** [kazeto/phillip#1]
When I executed 'make test', some errors occurred like this.

``` sh
 * ERROR * Cannot open file: "out/toy.lhs.xml"
 * ERROR * Cannot open file: "out/toy.ilp.xml"
 * ERROR * Cannot open file: "out/toy.sol.xml"
...
```

After I made the `out` directory 'make test' succeeded.

**Comment by kazeto** [comment]
Thank you for pointing out.
I have dealt with it on the version "phil.2.21".
